# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('choice', models.PositiveIntegerField(choices=[(1, '直播'), (2, '录播')])),
                ('category', models.PositiveIntegerField(choices=[(1, '艺术之光'), (2, '文明之光'), (3, '科技之光'), (4, '产业之光'), (5, '信仰的力量')])),
                ('getsrs', models.CharField(max_length=500)),
            ],
        ),
    ]
