# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='creator',
        ),
    ]
